from enum import Enum

class Actions(Enum):
    SUMMARIZE = "SUMMARIZE"
    REWRITE = "REWRITE"
    CHAT_WITH_DOC = "CHAT_WITH_DOC"
    CHAT_WITH_AI = "CHAT_WITH_AI"
    EXTRACT_IMPORTANT_DETAILS = "EXTRACT_IMPORTANT_DETAILS"